variable "authentication_method" {
  type        = string
  description = <<EOT
    The Vault authentication method to configure, currently the following values are supported:

    - [approle](https://www.vaultproject.io/docs/auth/approle)
    - [aws](https://www.vaultproject.io/docs/auth/aws)
    - [github](https://www.vaultproject.io/docs/auth/github)
    - [kubernetes](https://www.vaultproject.io/docs/auth/kubernetes)
    - [oidc](https://developer.hashicorp.com/vault/docs/auth/jwt/oidc-providers)

    @since 0.0.1
  EOT
}

variable "mount_path" {
  type        = string
  description = <<EOT
    The mount path of the authentication method

    @since 0.0.1
  EOT
}

variable "description" {
  type        = string
  description = <<EOT
    Description of the authentication method

    @since 0.0.1
  EOT
  default     = "Managed by Terraform"
}

variable "method_options" {
  type = object({
    /// Specifies the default token time-to-live. If set, this overrides the global default. Must be a [valid duration string][duration-string]
    ///
    /// @link {duration-string} https://pkg.go.dev/time#ParseDuration
    /// @since 0.0.1
    default_lease_ttl  = optional(string)
    /// Specifies the maximum token time-to-live. If set, this overrides the global default. Must be a [valid duration string][duration-string]
    ///
    /// @link {duration-string} https://pkg.go.dev/time#ParseDuration
    /// @since 0.0.1
    max_lease_ttl      = optional(string)
    /// Specifies whether to show this mount in the UI-specific listing endpoint.
    ///
    /// - unauth - Show this auth method in the web UI
    /// - hidden - Do not show this auth method in the web UI
    ///
    /// @enum unauth|hidden
    /// @since 0.0.1
    listing_visibility = optional(string)
  })

  description = <<EOT
    Configures common authentication method options

    ```terraform
    method_options = {
      default_lease_ttl = "1h"
      max_lease_ttl = "12h"
      listing_visibility = "unauth"
    }
    ```

    @since 0.0.1
  EOT
  default     = null
}

//
// AppRole
//

variable "approle_auth_roles" {
  type = map(object({
    /// Specifies blocks of IP addresses which can perform the login operation using this role
    ///
    /// @since 0.0.1
    secret_id_bound_cidrs = optional(list(string))
    /// The number of times any particular SecretID can be used to fetch a token from this AppRole, after which the SecretID will expire. A value of `0` or `null` will allow unlimited uses.
    ///
    /// @since 0.0.1
    secret_id_num_uses    = optional(number)
    /// Specify the token's TTL (time-to-live) in seconds
    ///
    /// @since 0.0.1
    token_ttl_seconds     = optional(number)
    /// Specify the token's max TTL (time-to-live) in seconds
    ///
    /// @since 0.0.1
    token_max_ttl_seconds = optional(number)
    /// A list of Vault policies to be attached to tokens generated by this role
    ///
    /// @since 0.0.1
    token_policies        = list(string)
  }))

  description = <<EOT
    Configures multiple AppRole auth roles for this authentication method. Input should be a map of `role_name = role_configuration` format.

    ```terraform
    approle_auth_roles = {
      "awx" = {
        secret_id_num_uses    = 3
        token_max_ttl_seconds = 3600
        token_policies        = ["awx"]
        token_ttl_seconds     = 600
      }
    }
    ```

    @since 0.0.1
  EOT
  default     = {}
}

//
// AWS
//

variable "aws_backend_credential" {
  type = object({
    /// Access key ID of an IAM user
    ///
    /// @since 0.0.1
    access_key_id     = string
    /// Secret access key of an IAM user
    ///
    /// @since 0.0.1
    secret_access_key = string
  })

  description = <<EOT
    Configuration of an AWS credential that Vault will use to validate authentication request across accounts. This is required if `authentication_method = aws`

    ```terraform
    aws_backend_credential = {
      access_key_id = "AKIA6XXXXXXXXXX"
      secret_access_key = "P+N4XXXXXXXXXXXXXXXXXXXXXX"
    }
    ```

    @since 0.0.1
  EOT
  default     = null
}

variable "aws_auth_roles" {
  type = map(object({
    /// The IAM role Vault assume to validate authentication requests to IAM roles in this role
    ///
    /// @since 0.0.1
    sts_role_arn             = string
    /// List of IAM arns that is allowed to authenticate using this role
    ///
    /// @since 0.0.1
    bound_iam_principal_arns = optional(list(string))
    /// Specify the token's TTL (time-to-live) in seconds
    ///
    /// @since 0.0.1
    token_ttl_seconds        = optional(number)
    /// Specify the token's max TTL (time-to-live) in seconds
    ///
    /// @since 0.0.1
    token_max_ttl_seconds    = optional(number)
    /// A list of Vault policies to be attached to tokens generated by this role
    ///
    /// @since 0.0.1
    token_policies           = list(string)
  }))

  description = <<EOT
    Configures an AWS authentication role in `RoleName = {RoleConfig}` format

    ```terraform
    aws_auth_roles = {
      "admin" = {
        sts_role_arn             = "arn:aws:iam::111122223333:role/vault-authentication-role"
        bound_iam_principal_arns = ["arn:aws:iam::111122223333:role/demo-role"]
        token_policies           = ["admin"]
      }
    }
    ```

    @since 0.0.1
  EOT
  default     = {}
}

//
// Github
//

variable "github_config" {
  type = object({
    /// The GitHub organization
    ///
    /// @since 0.0.1
    organization = string
    /// A map of GitHub teams (**team name must be slugified**) to be allowed to authenticate using this authentication endpoint and a list of policies associated to the team, in the `team_name = [policies]` format. ex: `{my-team = ["policy-1", "policy-2"]}`
    ///
    /// @since 0.0.1
    teams        = optional(map(list(string)))
    /// A map of GitHub users to be allowed to authenticate using this authentication endpoint and a list of policies associated to the users, in the `username = [policies]` format. ex: `{petersin = ["policy-1", "policy-2"]}`
    ///
    /// @since 0.0.1
    users        = optional(map(list(string)))
  })

  description = <<EOT
    Configuration of a GitHub authentication method. This is required if `authentication_method = github`

    ```terraform
    github_config = {
      organization = "FriendsOfTerraform"
      users = {"petersin0422" = ["octopus-api-policy"]}
    }
    ```

    @since 0.0.1
  EOT
  default     = null
}

//
// Kubernetes
//

variable "kubernetes_config" {
  type = object({
    /// The URL of the Kubernetes API server. Must be `https://`
    ///
    /// @since 0.0.1
    host               = string
    /// The CA certificate Vault will use to connect to the Kubernetes API server. Most providers (like AWS) returns this value in base64 encoded string, make sure the decoded value is passed in.
    ///
    /// @example "Kubernetes" #kubernetes
    /// @since 0.0.1
    ca_certificate     = string
    /// A Kubernetes service account JWT token that allow Vault to validate incoming authentication request with Kubernetes. Please refer to [this doc][kube-reviewer-jwt] for more information.
    ///
    /// @link {kube-reviewer-jwt} https://www.vaultproject.io/docs/auth/kubernetes#configuring-kubernetes
    /// @since 0.0.1
    token_reviewer_jwt = string
    /// The issuer of the `token_reviewer_jwt` token. Please refer to [this doc][kube-issuer] for more information.
    ///
    /// @link {kube-issuer} https://www.vaultproject.io/docs/auth/kubernetes#discovering-the-service-account-issuer
    /// @since 0.0.1
    issuer             = optional(string)
  })

  description = <<EOT
    Configuration of a Kubernetes authentication method. This is required if `authentication_method = kubernetes`

    ```terraform
    kubernetes_config = {
      host = "https://1D8D9CE84F575xxxxxxx.gr7.us-east-1.eks.amazonaws.com"
      ca_certificate = base64decode("LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tL...")
      token_reviewer_jwt = "eyJhbGciOiJSUzI1NiIsImtpZCI6IkJOMmw3eFUtVVZYOXRyQmZ1bmVUdW..."
    }
    ```

    @since 0.0.1
  EOT
  default     = null
}

variable "kubernetes_auth_roles" {
  type = map(object({
    /// A list of Kubernetes service account names that is permitted to authenticate using this role
    ///
    /// @since 0.0.1
    bound_service_account_names      = optional(list(string))
    /// A list of Kubernetes namespaces that is permitted to authenticate using this role
    ///
    /// @since 0.0.1
    bound_service_account_namespaces = optional(list(string))
    /// Specify the token's TTL (time-to-live) in seconds
    ///
    /// @since 0.0.1
    token_ttl_seconds                = optional(number)
    /// Specify the token's max TTL (time-to-live) in seconds
    ///
    /// @since 0.0.1
    token_max_ttl_seconds            = optional(number)
    /// A list of Vault policies to be attached to tokens generated by this role
    ///
    /// @since 0.0.1
    token_policies                   = list(string)
  }))

  description = <<EOT
    Configures multiple [Kubernetes auth roles][kubernetes-auth-role] for this authentication method. Input should be a map of `role_name = role_configuration` format.

    ```terraform
    kubernetes_auth_roles = {
      frontend = {
        bound_service_account_names      = ["frontend"]
        bound_service_account_namespaces = ["webapp"]
        token_policies                   = ["webapp-frontend"]
      }
    }
    ```

    @link {kubernetes-auth-role} https://www.vaultproject.io/docs/auth/kubernetes#configuration
    @since 0.0.1
  EOT
  default     = {}
}

//
// OIDC
//

variable "oidc_config" {
  type = object({
    /// The default role to use if none is provided during login
    ///
    /// @since 0.0.1
    default_role  = optional(string)
    /// The OIDC Discovery URL, without any .well-known component (base path).
    ///
    /// @example "OIDC" #oidc
    /// @since 0.0.1
    discovery_url = string
    /// Client ID used for OIDC backends
    ///
    /// @since 0.0.1
    client_id     = string
    /// Client Secret used for OIDC backends
    ///
    /// @since 0.0.1
    client_secret = string
  })

  description = <<EOT
    Configuration of an OIDC authentication method. This is required if `authentication_method = oidc`

    ```terraform
    oidc_config = {
      default_role = "tech-infra-cloudops"
      discovery_url = "https://login.microsoftonline.com/abcdef-1111-2222-abcd-11112222aaaa/v2.0"
      client_id = "8ad6e653-f37e-4a33-80fe-xxxxxxxxxxxx"
      client_secret = "some-secret...."
    }
    ```

    @since 0.0.1
  EOT
  default     = null
}

variable "oidc_auth_roles" {
  type = map(object({
    /// The claim to use to uniquely identify the user
    ///
    /// @since 0.0.1
    user_claim            = optional(string)
    /// A map of claims that restrict only the identity that has matching claims in its token. For example, `this identity must be in groups = <group_id>`
    ///
    /// @since 0.0.1
    bound_claims          = optional(map(string))
    /// The claim to use to uniquely identify the set of groups to which the user belongs
    ///
    /// @since 0.0.1
    groups_claim          = optional(string)
    /// A list of OIDC scopes to be used with an OIDC role
    ///
    /// @since 0.0.1
    oidc_scopes           = optional(list(string))
    /// A list of redirect URIs where authentication responses can be redirected back to the caller
    ///
    /// @since 0.0.1
    allowed_redirect_uris = optional(list(string))
    /// Specify the token's TTL (time-to-live) in seconds
    ///
    /// @since 0.0.1
    token_ttl_seconds     = optional(number)
    /// Specify the token's max TTL (time-to-live) in seconds
    ///
    /// @since 0.0.1
    token_max_ttl_seconds = optional(number)
    /// A list of Vault policies to be attached to tokens generated by this role
    ///
    /// @since 0.0.1
    token_policies        = list(string)
  }))

  description = <<EOT
    Configures multiple OIDC auth roles for this authentication method. Input should be a map of `role_name = role_configuration` format.

    ```terraform
    oidc_auth_roles = {
      tech-infra-cloudops = {
        user_claim = "email"

        bound_claims = {
          groups = "f427664f-4c51-xxxx-xxxx-xxxx" # Tech-Infra-CloudOps
        }

        oidc_scopes       = ["https://graph.microsoft.com/.default"]
        groups_claim      = "groups"

        allowed_redirect_uris = [
          "https://vault.friendsofterraform.com/ui/vault/auth/$${vault_jwt_auth_backend.azure_ad.path}/oidc/callback",
          "http://localhost:8250/oidc/callback"
        ]

        token_policies = ["cloudops-users"]
      }
    }
    ```

    @since 0.0.1
  EOT
  default     = {}
}
